"""Add publication_date to Event

Revision ID: 025faea8a158
Revises: c3d279943ef2
Create Date: 2025-10-08 18:25:01.097193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025faea8a158'
down_revision = 'c3d279943ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_date', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('publication_date')

    # ### end Alembic commands ###
