"""Manually add kb_id to KnowledgeBaseArticle

Revision ID: 1de6d7bb5e92
Revises: ce696aee84f6
Create Date: 2025-10-14 11:21:33.208355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de6d7bb5e92'
down_revision = 'ce696aee84f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kb_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_knowledge_base_article_kb_id', ['kb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base_article', schema=None) as batch_op:
        batch_op.drop_constraint('uq_knowledge_base_article_kb_id', type_='unique')
        batch_op.drop_column('kb_id')

    # ### end Alembic commands ###
