"""Initial migration

Revision ID: 30972f960625
Revises: 
Create Date: 2025-10-06 14:52:07.145668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30972f960625'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_suspended')
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
