"""alter_event_date_to_date

Revision ID: 43dc3faeec8d
Revises: e8b8d0b961cb
Create Date: 2025-10-07 19:19:42.569902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43dc3faeec8d'
down_revision = 'e8b8d0b961cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.alter_column('event_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        # A linha drop_constraint foi removida para compatibilidade com SQLite
        batch_op.create_foreign_key(batch_op.f('fk_event_creator_id_user'), 'user', ['creator_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=False))
        # A linha drop_constraint foi removida para compatibilidade com SQLite
        batch_op.create_foreign_key(batch_op.f('fk_event_author_id_user'), 'user', ['author_id'], ['id'])
        batch_op.alter_column('event_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
