"""Adiciona campos de bloqueio de login

Revision ID: 51a097dd448d
Revises: 5a57f625c7ec
Create Date: 2025-10-10 19:46:30.232531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a097dd448d'
down_revision = '5a57f625c7ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_locked')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
