"""Add is_archived to AccessRequest

Revision ID: 6df8d9c13516
Revises: 1de6d7bb5e92
Create Date: 2025-10-14 19:48:37.394065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df8d9c13516'
down_revision = '1de6d7bb5e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_request', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
