"""Add KnowledgeBaseArticle model

Revision ID: 76538c099dda
Revises: 51a097dd448d
Create Date: 2025-10-13 18:19:44.790504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76538c099dda'
down_revision = '51a097dd448d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_base_article')
    # ### end Alembic commands ###
