"""Add image_url to News and Event models

Revision ID: c3d279943ef2
Revises: 43dc3faeec8d
Create Date: 2025-10-08 14:06:23.515981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d279943ef2'
down_revision = '43dc3faeec8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
