
"""Add kb_id to KnowledgeBaseArticle

Revision ID: ce696aee84f6
Revises: 76538c099dda
Create Date: 2025-10-13 19:52:41.802750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce696aee84f6'
down_revision = '76538c099dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kb_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint("uq_knowledge_base_article_kb_id", ['kb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base_article', schema=None) as batch_op:
        batch_op.drop_constraint("uq_knowledge_base_article_kb_id", type_='unique')
        batch_op.drop_column('kb_id')

    # ### end Alembic commands ###
